# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ECE-C302/prelab5/adder_fpga/adder_fpga.cache/wt [current_project]
set_property parent.project_path D:/ECE-C302/prelab5/adder_fpga/adder_fpga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  D:/ECE-C302/prelab5/adder_fpga/adder_fpga.srcs/sources_1/new/p1_pack.vhd
  D:/ECE-C302/prelab5/adder_fpga/adder_fpga.srcs/sources_1/new/add3bits.vhd
  D:/ECE-C302/prelab5/adder_fpga/adder_fpga.srcs/sources_1/new/serial_adder.vhd
  D:/ECE-C302/prelab5/adder_fpga/adder_fpga.srcs/sources_1/new/sh_reg.vhd
  D:/ECE-C302/prelab5/adder_fpga/adder_fpga.srcs/sources_1/new/control.vhd
  D:/ECE-C302/prelab5/adder_fpga/adder_fpga.srcs/sources_1/new/adder.vhd
  D:/ECE-C302/prelab5/adder_fpga/adder_fpga.srcs/sources_1/new/test_adder.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ECE-C302/prelab5/adder_fpga/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/ECE-C302/prelab5/adder_fpga/Basys3_Master.xdc]


synth_design -top test_adder -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_adder.dcp

catch { report_utilization -file test_adder_utilization_synth.rpt -pb test_adder_utilization_synth.pb }
