# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ECE-C302/hw3/thres_gate/thres_gate.cache/wt [current_project]
set_property parent.project_path D:/ECE-C302/hw3/thres_gate/thres_gate.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  D:/ECE-C302/hw3/thres_gate/thres_gate.srcs/sources_1/new/thres_gate.vhd
  D:/ECE-C302/hw3/thres_gate/thres_gate.srcs/sources_1/new/thres_test.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ECE-C302/hw3/thres_gate/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/ECE-C302/hw3/thres_gate/Basys3_Master.xdc]


synth_design -top thres_test -part xc7a35tcpg236-1


write_checkpoint -force -noxdef thres_test.dcp

catch { report_utilization -file thres_test_utilization_synth.rpt -pb thres_test_utilization_synth.pb }
