# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cdc75/Desktop/Lab/hw1/unsignedmult/unsignedmult.cache/wt [current_project]
set_property parent.project_path C:/Users/cdc75/Desktop/Lab/hw1/unsignedmult/unsignedmult.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/cdc75/Desktop/Lab/hw1/unsignedmult/unsignedmult.srcs/sources_1/new/reg.vhd
  C:/Users/cdc75/Desktop/Lab/hw1/unsignedmult/unsignedmult.srcs/sources_1/new/unsignedmult.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/cdc75/Desktop/Lab/hw1/unsignedmult/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/cdc75/Desktop/Lab/hw1/unsignedmult/Basys3_Master.xdc]


synth_design -top unsignedmult -part xc7a35tcpg236-1


write_checkpoint -force -noxdef unsignedmult.dcp

catch { report_utilization -file unsignedmult_utilization_synth.rpt -pb unsignedmult_utilization_synth.pb }
